### ISSUE TITLE
Icons aren't loading in the mat-icon-buttons?

### ISSUE THREAD

**Issue by kelliev** [dnyaneshwargiri/angular-material-3#1]
This is so great, thank you for providing this repo for a demo. I've got everything working for myself, but the icons aren't loading. It is being imported correctly (as far as I can tell), but not displaying in the browser after a build?

<img width="1844" alt="Screenshot 2024-03-28 at 1 19 52 PM" src="https://github.com/dnyaneshwargiri/angular-material-3/assets/40643335/e8150b92-b5c8-4154-9fe2-cf1b5ae64e12">

**Comment by dnyaneshwargiri** [comment]
@kelliev it was beacuase you were using them in offline mode.
Never mind, I pushed a new commit to add support to make icons work even if client is disconnected from internet.

<img width="1417" alt="image" src="https://github.com/dnyaneshwargiri/angular-material-3/assets/34788823/60cd28a4-89ea-4fe3-be73-cc543fe9b183">

**Comment by dnyaneshwargiri** [comment]
It is important to note if you want to use custom fonts or another fonts, you'll need to download that font and put in `assets/fonts/` and update `google-font.css` with respective font url.

**Comment by kelliev** [comment]
Thank you for the quick response.

I wasn’t offline … but I will do a git pull.
One last question: when I compile to prod, it spits out its own directory separate from the original project but I don’t know how to upload it to the server (what path should it be?)
I tried the following commands:

ng build --base-href /ng-starter-kit/angular-material-3/
ng build /ng-starter-kit/angular-material-3/
ng build /ng-starter-kit/
ng build --base-href /ng-starter-kit/
ng build /angular-material-3/
ng build --base-href /angular-material-3/

Kellie

**Comment by dnyaneshwargiri** [comment]
okay @kelliev, so problem I fixed is I downloaded fonts and css which were previously being served by google.cdn and put it locally. From your question it seems you've angular application viz.`ng-starter-kit` you can either integrate this demo as single app or you have to specify multi project settings in `angular.json`  something like 

`"projects":` { 
  "ng-starter-kit": {...},
  "material-3-demo" : {...}
`
& there is prod build configured as below

![image](https://github.com/dnyaneshwargiri/angular-material-3/assets/34788823/0e35eabc-8981-4e40-8941-e1be4f512010)
